name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t vuejs-s3-fe/dockerize-vuejs-app .

    - name: run docker
      run: docker run -it -p 6001:6000 --rm --name dockerize-vuejs-app-1 vuejs-s3-fe/dockerize-vuejs-app